#FROM ubuntu:23.10
FROM python:3.9.17
COPY . /digits/
#RUN apt-get update
#RUN apt-get install -y python3 python3-pip
RUN pip3 install -r /digits/requirements.txt
WORKDIR /digits
# CMD ["pytest"]
CMD ["python", "digits.py", "0.3", "0.3", "0.002", "0.2", "20"]